services:
  php:
    user: ${USER_ID:-root}:${GROUP_ID:-root}
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal mode=debug
      PHP_IDE_CONFIG: serverName=queue-bench
      XDEBUG_TRIGGER: yes
    volumes:
      - .:/app
      - ./runtime/.composer:/root/.composer

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - ${RABBIT_PORT:-5672}:5672
      - ${RABBIT_MANAGEMENT_PORT:-15672}:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 3s
      timeout: 5s
      retries: 3
